version: '3.9'
services:
  app:
    build:
      context: ../..
      dockerfile: deploy/dev/Dockerfile
    container_name: telegram_admin_app_dev
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    volumes:
      - ../../apps:/app/apps
      - ../../config:/app/config
    networks:
      - telegram_admin_network

  postgres:
    image: postgres:15
    container_name: telegram_admin_postgres_dev
    environment:
      POSTGRES_DB: telegram_admin_api_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devpassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - telegram_admin_network

volumes:
  postgres_data_dev:

networks:
  telegram_admin_network:
    driver: bridge
