version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    env_file:
      - ./env_file
    container_name: ${DB_HOST}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGPORT: ${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    networks:
      - telegram_admin_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Elixir Application
  app:
    image: telegram-admin-api:latest
    env_file:
      - ./env_file
    container_name: APP_CONTAINER_NAME
    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - telegram_admin_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy
  nginx:
    image: telegram-admin-nginx:latest
    env_file:
      - ./env_file
    container_name: NGINX_CONTAINER_NAME
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/telegram-admin-api/certbot/conf:/etc/letsencrypt
      - /opt/telegram-admin-api/certbot/www:/var/www/certbot
    depends_on:
      - app
    networks:
      - telegram_admin_network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  # Certbot for SSL certificates
  certbot:
    image: certbot/certbot
    env_file:
      - env_file
    container_name: CERTBOT_CONTAINER_NAME
    volumes:
      - /opt/telegram-admin-api/certbot/conf:/etc/letsencrypt
      - /opt/telegram-admin-api/certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email -d ${HOST:-body-architect.ru}
    networks:
      - telegram_admin_network

volumes:
  postgres_data:

networks:
  telegram_admin_network:
    driver: bridge 