import Config

# Configure your database
config :core, Core.Repo,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :admin_api, AdminApiWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "your-secret-key-base-here-change-in-development"

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Code reloader configuration for API-only application
config :admin_api, :code_reloader,
  watch_paths: [
    "../../lib",
    "../../priv",
    "../../config",
    "../../test"
  ]

# Configure ports for development
# Use System.get_env for consistency, with defaults for convenience.
app_port_http = System.get_env("APP_PORT_HTTP", "4000") |> String.to_integer()
telegram_port_webhook = System.get_env("TELEGRAM_PORT_WEBHOOK", "4002") |> String.to_integer()

config :admin_api, AdminApiWeb.Endpoint, http: [ip: {127, 0, 0, 1}, port: app_port_http]

config :telegex,
  telegram_port_webhook: telegram_port_webhook

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
