{application,table_rex,
             [{modules,['Elixir.TableRex','Elixir.TableRex.Cell',
                        'Elixir.TableRex.Column','Elixir.TableRex.Error',
                        'Elixir.TableRex.Renderer',
                        'Elixir.TableRex.Renderer.Text',
                        'Elixir.TableRex.Renderer.Text.Meta',
                        'Elixir.TableRex.Table']},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger]},
              {description,"Generate configurable text-based tables for display (ASCII & more)"},
              {registered,[]},
              {vsn,"4.1.0"}]}.
